<datalist id="names">
  <option value="ALBERT SANJAYA"></option>
  <option value="ANDREW"></option>
  <option value="ANGELICA CAHAYA LAZUARDI"></option>
  <option value="ANGGIE APRILIA DEVINA"></option>
  <option value="CATHERINE CALISTA"></option>
  <option value="CHILWIN"></option>
  <option value="CINDY ANGELIA LEONARDY"></option>
  <option value="CLARISSA ELLEN SIM"></option>
  <option value="CORRINA CRISTY CHEN"></option>
  <option value="CRESTELLA SURYA"></option>
  <option value="CRISYE YOUNG"></option>
  <option value="DARREN LYSS CHANDRA"></option>
  <option value="DARREN WONG"></option>
  <option value="DAVID"></option>
  <option value="DHARMA SATRIYA GAUTAMA"></option>
  <option value="DODVIN ANGDERICO"></option>
  <option value="EARLEANE CALISTA"></option>
  <option value="EDDRICK"></option>
  <option value="ELQYRO RAPHAEL YU"></option>
  <option value="EVAN STANLEY"></option>
  <option value="FELICE DAVINCCI WILIDYO"></option>
  <option value="FELYCHIA ZUFTI"></option>
  <option value="GRACE CORRINE"></option>
  <option value="GRACE OCTAVIUS HAVILAH"></option>
  <option value="HARVANY LIEWIN"></option>
  <option value="JEFF HANSENN ESTOMIHI SILALAHI"></option>
  <option value="JESSLYN"></option>
  <option value="JESSY TANAYA"></option>
  <option value="JOLIVIA"></option>
  <option value="JONG FILBERT ANTONIUS"></option>
  <option value="JOVAN PUTRA PANDAWA"></option>
  <option value="JUSTIN ETHAN"></option>
  <option value="KAYLA RAINE WIDJAJA"></option>
  <option value="MARGARETH JOY FEBRIANTY PAKPAHAN"></option>
  <option value="ORLANDO EDWARD ONGAH"></option>
  <option value="RICHARD ANDERSON"></option>
  <option value="RITCHIE GUANCHELO"></option>
  <option value="SHAWN HUBERT"></option>
  <option value="SHEZA CHEN"></option>
  <option value="VINCENT WESLEY"></option>
  <option value="WILBERT YANG JAYA"></option>
  <option value="WILSON MASLIE"></option>
  <option value="YOHANES ZEFANYA WILLIEM"></option>
</datalist>
